#!/usr/bin/env bash
# regen-status.sh — Regenerate services/status.md from impl journals
#
# Impl journals are the write authority for service state.
# status.md is a derived, machine-generated view.
# Manual edits to status.md are prohibited.
#
# Usage:
#   regen-status.sh [--check] [--skills-dir <path>]
#
# --check   : validate consistency without writing (exit 0=consistent, 1=drift)
# --skills-dir : path to shared-skills root (default: auto-detect from script location)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_DIR="${REPO_ROOT}/shared-skills"
CHECK_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=true; shift ;;
    --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

IMPL_DIR="${SKILLS_DIR}/apf-warning-impl/services"
STATUS_FILE="${SKILLS_DIR}/genai-warning-pipeline/services/status.md"

if [[ ! -d "$IMPL_DIR" ]]; then
  echo "ERROR: impl services dir not found: $IMPL_DIR" >&2
  exit 1
fi

# Parse last verdict from an impl journal file.
# Looks for known verdict patterns in the file content.
# Returns: STATUS or "STALE" if no recognized pattern found.
parse_verdict() {
  local file="$1"
  local content
  content=$(cat "$file")

  # Priority order: most definitive patterns first
  if echo "$content" | grep -qi "VERIFIED"; then
    # Check for re-verification pass
    if echo "$content" | grep -q "✅.*PASS.*VERIFIED\|✅ VERIFIED\|VERIFIED (2026"; then
      echo "VERIFIED"
      return
    fi
  fi

  if echo "$content" | grep -qi "BLOCKED_ONLY"; then
    echo "BLOCKED_ONLY"
    return
  fi

  if echo "$content" | grep -qi "EXCLUDED\|INFRA.*WEBSOCKET\|자동화 불가"; then
    echo "EXCLUDED"
    return
  fi

  if echo "$content" | grep -qi "Current Status.*TESTING\|TESTING 재개"; then
    echo "TESTING"
    return
  fi

  if echo "$content" | grep -qi "WAITING_RESULT\|결과 대기"; then
    echo "WAITING_RESULT"
    return
  fi

  if echo "$content" | grep -qi "✅.*DONE\|DONE"; then
    echo "DONE"
    return
  fi

  echo "STALE"
}

# Detect strategy deviation marker
has_deviation() {
  local file="$1"
  grep -qi "STRATEGY_DEVIATION" "$file" && echo "yes" || echo "no"
}

# Extract service_id from filename: {service_id}_impl.md
extract_service_id() {
  local filename
  filename=$(basename "$1")
  echo "${filename%_impl.md}"
}

# Collect all impl journals
declare -A VERDICTS
declare -A DEVIATIONS
STALE_COUNT=0

for impl_file in "${IMPL_DIR}"/*_impl.md; do
  [[ -f "$impl_file" ]] || continue
  service_id=$(extract_service_id "$impl_file")
  verdict=$(parse_verdict "$impl_file")
  deviation=$(has_deviation "$impl_file")

  VERDICTS["$service_id"]="$verdict"
  DEVIATIONS["$service_id"]="$deviation"

  if [[ "$verdict" == "STALE" ]]; then
    ((STALE_COUNT++))
    echo "⚠ STALE: ${service_id} — no recognized verdict in impl journal" >&2
  fi
  if [[ "$deviation" == "yes" ]]; then
    echo "⚠ STRATEGY_DEVIATION: ${service_id}" >&2
  fi
done

if $CHECK_ONLY; then
  # In check mode, compare current status.md against parsed verdicts
  drift=0
  for service_id in "${!VERDICTS[@]}"; do
    current=$(grep -i "$service_id" "$STATUS_FILE" 2>/dev/null | head -1 || true)
    parsed="${VERDICTS[$service_id]}"
    if [[ -n "$current" ]] && ! echo "$current" | grep -qi "$parsed"; then
      echo "DRIFT: ${service_id} — status.md differs from impl journal (impl=${parsed})" >&2
      ((drift++))
    fi
  done
  if [[ $drift -gt 0 || $STALE_COUNT -gt 0 ]]; then
    echo "Check failed: ${drift} drift(s), ${STALE_COUNT} stale" >&2
    exit 1
  fi
  echo "Check passed: all consistent"
  exit 0
fi

# Generate new status.md
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
cat > "$STATUS_FILE" << 'HEADER'
# Warning Pipeline — Service Status

> **This file is auto-generated by `regen-status.sh`.** Do not edit manually.
> Source of truth: `apf-warning-impl/services/{service_id}_impl.md`

HEADER

echo "| Service | service_id | Status | Testable | Last synced | Notes |" >> "$STATUS_FILE"
echo "|---------|-----------|--------|----------|-------------|-------|" >> "$STATUS_FILE"

# Service display names (maintain order)
declare -A DISPLAY_NAMES=(
  [chatgpt]="ChatGPT"
  [claude]="Claude"
  [perplexity]="Perplexity"
  [genspark]="Genspark"
  [gemini]="Gemini"
  [grok]="Grok"
  [notion]="Notion AI"
  [github_copilot]="GitHub Copilot"
  [gamma]="Gamma"
  [m365_copilot]="M365 Copilot"
)

# Testable flags (from Full Rescan 2026-04-07 data)
declare -A TESTABLE=(
  [chatgpt]="yes"
  [claude]="yes"
  [perplexity]="yes"
  [genspark]="yes"
  [gemini]="conditional"
  [grok]="no"
  [notion]="no"
  [github_copilot]="conditional"
  [gamma]="yes"
  [m365_copilot]="no"
)

# Ordered service list
ORDERED_SERVICES=(chatgpt claude perplexity genspark gemini grok notion github_copilot gamma m365_copilot)

for sid in "${ORDERED_SERVICES[@]}"; do
  name="${DISPLAY_NAMES[$sid]:-$sid}"
  verdict="${VERDICTS[$sid]:-UNKNOWN}"
  testable="${TESTABLE[$sid]:-unknown}"
  deviation="${DEVIATIONS[$sid]:-no}"
  notes=""

  if [[ "$verdict" == "STALE" ]]; then
    notes="⚠ STALE — regen could not parse verdict"
  fi
  if [[ "$deviation" == "yes" ]]; then
    notes="${notes:+$notes, }⚠ STRATEGY_DEVIATION"
  fi

  echo "| ${name} | ${sid} | ${verdict} | ${testable} | ${TIMESTAMP} | ${notes} |" >> "$STATUS_FILE"
done

# Append priority section
cat >> "$STATUS_FILE" << 'PRIORITY'

## 서비스 우선순위

→ 우선순위와 난이도는 impl journal의 최신 상태를 기반으로 판단한다.
DONE/VERIFIED 서비스는 제외. BLOCKED_ONLY는 새 전략 확보 시만 재시도.

## Experience Files

| Service | Experience files |
|---------|-----------------|
| ChatGPT | `genai-apf-pipeline/services/chatgpt_design.md`, `apf-warning-impl/services/chatgpt_impl.md` |
| Claude | `apf-warning-impl/services/claude_impl.md` |
| Perplexity | `genai-apf-pipeline/services/perplexity_design.md`, `apf-warning-impl/services/perplexity_impl.md` |
| Genspark | `apf-warning-impl/services/genspark_impl.md` |
| Gemini | `genai-apf-pipeline/services/gemini_design.md`, `apf-warning-impl/services/gemini_impl.md` |
| Grok | `genai-apf-pipeline/services/grok_design.md`, `apf-warning-impl/services/grok_impl.md` |
| GitHub Copilot | `genai-apf-pipeline/services/github-copilot_design.md`, `apf-warning-impl/services/github_copilot_impl.md` |
| Gamma | `genai-apf-pipeline/services/gamma_design.md`, `apf-warning-impl/services/gamma_impl.md` |
| M365 Copilot | `genai-apf-pipeline/services/m365-copilot_design.md`, `apf-warning-impl/services/m365_copilot_impl.md` |
| Notion AI | `genai-apf-pipeline/services/notion_design.md`, `apf-warning-impl/services/notion_impl.md` |
PRIORITY

echo "" >> "$STATUS_FILE"
echo "---" >> "$STATUS_FILE"
echo "" >> "$STATUS_FILE"
echo "_Last regenerated: ${TIMESTAMP} by regen-status.sh_" >> "$STATUS_FILE"

echo "✅ status.md regenerated (${#VERDICTS[@]} services, ${STALE_COUNT} stale)"
